### ISSUE TITLE
Piping responses to create a chain of prompt execution

### ISSUE THREAD

**Issue by varghese-ascalonic** [Ascalonic/PromptML#4]
A major feature where as a user I should be able to create multiple prompt files where response of one prompt is piped into the input of another prompt and into another and so on.

Here is an expected prompt system that generates a motivational quote and we pass it into another prompt which verifies whether some fact is correct or incorrect

quote.prompt
```yaml
inputs:
  - type: scalar
    name: author
engine: gpt-4-turbo-preview
role: You are a helpful assistant designed to output motivational quotes
prompt: "Generate a motivational quote by {{author}}"

output: motivationalQuote #store the output in a variable

askNext: verify.prompt. #specify the next prompt file to execute
```

verify.prompt
```yaml
inputs:
  - type: scalar
    name: motivationalQuote #this prompt should be able to access the global variables

role: You are a helpful assistant designed to verify a quote was said by the author or not
prompt: "Was {{motivationalQuote}} really written by the author? output yes or no"

output: motivationalQuote #we pass this from the prompt so that it can be received by the application

- type: response
  expected: [ yes ]
```

This is an absolute f*ckfest of a feature and needs some serious modification to the code and tests.
