### ISSUE TITLE
Support for other input types

### ISSUE THREAD

**Issue by varghese-ascalonic** [Ascalonic/PromptML#5]
Right now PromptML only supports `scalar` which denotes single values like a number or a string.

As a user I should be able to specify other data types as well - like `vector` (a 1-D list) and `object` (like a JSON object).

When putting the template values into the prompt, user will have more flexibility in specifying the value.

eg:
a vector
```yaml
inputs:
  - type: vector
    name: authors
prompt: "Generate a motivational quote by the authors {{ authors[0] }} or {{ authors[1] }}"
```

or object
```yaml
inputs:
  - type: object
    name: resume
prompt: "Which country is {{ resume.city }} located in? eg: England, India etc"
```

Who knows, maybe in the future we can do other types as well, for example - `image`. Not now tho.
